"""add_news

Revision ID: 302ee99c2e64
Revises: 1d646918793a
Create Date: 2021-12-26 21:49:20.381021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302ee99c2e64'
down_revision = '1d646918793a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'resrqwr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('resrqwr', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
