"""add name

Revision ID: 5f31ab8723e4
Revises: 49f4ed990e2b
Create Date: 2021-12-25 13:45:46.828316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f31ab8723e4'
down_revision = '49f4ed990e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    # ### end Alembic commands ###
